# Generated by Django 4.2.1 on 2023-06-05 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.IntegerField(default=0)),
                ('timein', models.TimeField(blank=True, default='00:00', null=True)),
                ('timeout', models.TimeField(default='00:00')),
                ('date', models.DateField(auto_now_add=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.emp')),
            ],
        ),
    ]
