# Generated by Django 4.2.2 on 2023-06-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_emp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='img/'),
        ),
    ]
