# Generated by Django 4.2.2 on 2023-06-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_emp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='skill',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
